# Generated by Django 2.2.10 on 2021-01-25 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.UUIDField(default=uuid.UUID('0bd6fd23-da6f-4dd2-94e8-3ed3a229ad08'), editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 1, 25, 21, 22, 50, 319665))),
                ('author', models.TextField(default='')),
                ('title', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.UUID('f4507803-e876-4c22-8ae5-57382dcf013d'), editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 1, 25, 21, 22, 50, 320663))),
                ('author', models.TextField(default='')),
                ('comment_text', models.TextField(default='')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddimental.Submission')),
            ],
        ),
    ]
