# Generated by Django 2.2.10 on 2021-02-01 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddimental', '0002_auto_20210125_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 12, 30, 13, 472453)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 12, 30, 13, 472453)),
        ),
    ]
