# Generated by Django 2.2.10 on 2021-02-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddimental', '0008_auto_20210201_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='author',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.TextField(default='', null=True),
        ),
    ]
